# Generated by Django 3.1.7 on 2021-06-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreport',
            name='option',
        ),
        migrations.RemoveField(
            model_name='orderreport',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderreport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderreport',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderreport',
            name='content',
            field=models.TextField(default=True),
        ),
    ]
