# Generated by Django 3.1.7 on 2021-06-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210620_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
