# Generated by Django 3.1.7 on 2021-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210620_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
