# Generated by Django 3.1.7 on 2021-06-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210620_1826'),
        ('store', '0002_auto_20210620_1954'),
    ]

    operations = [
    ]
