# Generated by Django 3.1.7 on 2021-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210324_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
