# Generated by Django 3.1.7 on 2021-06-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20210623_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreport',
            old_name='createdAt',
            new_name='created',
        ),
        migrations.AddField(
            model_name='orderreport',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
