# Generated by Django 3.1.7 on 2021-06-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_orderreport_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
