# Generated by Django 3.1.7 on 2021-05-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210407_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='category',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='New', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='order_date',
            field=models.DateTimeField(verbose_name='Order Date'),
        ),
    ]
