# Generated by Django 3.2.3 on 2021-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210520_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Baby boy clothes', 'Baby boy clothes'), ('Baby girl clothes', 'Baby girl clothes'), ('Baby supplies', 'Baby supplies'), ('Mom and baby couple', 'Mom and baby couple')], max_length=255, null=True),
        ),
    ]
