# Generated by Django 3.1.7 on 2021-05-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210526_2044'),
        ('store', '0023_alter_product_category'),
    ]

    operations = [
    ]
